version: '3.1'

services:
  cron:
    image: 127.0.0.1:5000/reunion_cron
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reunion:/home/app/reunion
      - ./main.py:/home/app/main.py

networks:
  default:
    external:
      name: svc-overlay-network
